from .base import *  # noqa


# Archiving settings

MAX_UNARCHIVED_TWEETS = 100
ARCHIVING_INTERVAL = 10  # In seconds


# Monitoring settings

TIME_WINDOW_LENGTH_IN_MINUTES = 1
TIME_WINDOW_INTERVAL_IN_MINUTES = 1
WARNING_THRESHOLD_DIFFERENCE = 1
