from .base import *  # noqa


# Archiving settings

MAX_UNARCHIVED_TWEETS = 100000


# Monitoring settings

TIME_WINDOW_LENGTH_IN_MINUTES = 15
TIME_WINDOW_INTERVAL_IN_MINUTES = 5
WARNING_THRESHOLD_DIFFERENCE = 10
